test: fix workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,11 +35,21 @@ jobs:
       - name: Move artifacts to output directory
         run: |
           mkdir -p output
-          mv dist/* output/
+          ls -lR dist
+          find dist/synq_linux_amd64_v1 -type f -name "synq" -exec cp {} output/synq \;
           ls -lR output
-      
+
+          if [ ! -f output/synq ]; then
+            echo "Error: synq binary not found in dist directory."
+            exit 1
+          fi
+                
       - name: Test Docker Compose
-        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from tester
+        run: docker compose -f docker-compose.test.yml up
+
+      - name: Clean repo
+        run: |
+          rm -rf output
 
       - name: Run GoReleaser
         uses: goreleaser/goreleaser-action@v6
